### ISSUE TITLE
check_api_key rejects valid keys

### ISSUE THREAD

**Issue by kynan** [puentesarrin/pymongolab#5]
The `check_api_key` [function](https://github.com/puentesarrin/pymongolab/blob/master/mongolabclient/validators.py#L19) does not cover all valid API key formats. My key is in the format `[a-z0-9]{23}-[a-z0-9]{8}`.

**Comment by puentesarrin** [comment]
Thanks! You're right!

But I have try regenerate my key for testing and this includes underscore too.

**Comment by puentesarrin** [comment]
What about this pattern: `^[a-zA-Z0-9_-]{32}$`? Works for you?

**Comment by puentesarrin** [comment]
@benzenwen Please, help us to clarify what's the pattern to validate the keys.

**Comment by kynan** [comment]
Yep, that regex works for me, thanks.

**Comment by puentesarrin** [comment]
Ok, I have updated the regex to `^[a-z0-9]{24}|[a-zA-Z0-9_-]{32}$` for support new and old API key format.
