### ISSUE TITLE
Is there a proper way to make a connection while hiding the API key? 

### ISSUE THREAD

**Issue by antsankov** [puentesarrin/pymongolab#6]
I am working on a simple Flask web server that is making a connection to a Mongolabs DB. I need to host this on Github for a class, but I am unsure of the proper way to obfuscate the API key in my source when I have to use the line: 

`connection = Connection("API Key")`

1) Is there a standard way to do this in this type of situation, or does my API key have to be visible to whoever can view the source? 
2) Does this mean, someone could theoretically use my API key in a separate application to modify my DB? 

I was trying to look at the [documentation](http://pymongolab.puentesarr.in/en/latest/examples.html#making-a-connection) but was unable to find an answer if this is possible.

**Comment by puentesarrin** [comment]
I faced with the same issue and this is the reason the tests are not in the repo. However, I think you can "hide" you API key from your application code by getting it from a environment variable. Just do the following:

```
$ export PYMONGOLAB_KEY="MyKey"
$ echo $PYMONGOLAB_KEY
MyKey
$ python
Python 2.7.3 (default, Dec 18 2014, 19:10:20) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> print os.environ['PYMONGOLAB_KEY']
MyKey
>>> 
```

What do you think?

**Comment by antsankov** [comment]
That actually looks like a great solution. I'm curious why API key is tied to account users as opposed to DB users. If we could generate an API key for a DB user, we can simply give it read-only privileges and post that key instead. 

Having to make a new account user seems like overkill.

**Comment by puentesarrin** [comment]
Yeah! That's an implementation detail of MongoLab. I even think it's not a very safe way to make this kind of service.

Many thanks for your question!
